# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: dolphinnext-trimmomatic
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - umi_tools=0.5.5
