# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: dolphinnext
channels:
  - conda-forge
  - bioconda
  - defaults
  - bih-cubi
dependencies:
  - umi_tools=0.5.4
  - python=2.7
  - pysam=0.8.4
  - numpy=1.16.5
  - scipy=1.2.1
  - biopython=1.76
  - openjdk=11.0.9.1
  - r
  - bcl2fastq2